# Generated by Django 2.2.24 on 2022-11-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patients', '0001_initial'),
        ('Dentists', '0001_initial'),
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_reason', models.CharField(choices=[('GC', 'General Consultation'), ('DC', 'Dental cleaning'), ('CR', 'Crowns'), ('BR', 'Braces'), ('TW', 'Teeth whitening')], default='CG', max_length=2)),
                ('date', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Clinic')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dentists.Dentist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.Patients')),
            ],
        ),
    ]
