# Generated by Django 2.2.24 on 2022-11-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_auto_20221120_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hour',
        ),
    ]
