# Generated by Django 2.2.24 on 2022-11-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_remove_appointment_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hour',
            field=models.TimeField(blank=True, null=True, verbose_name=['%I:%H %p']),
        ),
    ]
