# Generated by Django 2.2.24 on 2023-03-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0005_auto_20221120_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hour',
            field=models.CharField(choices=[('GC', 'General Consultation'), ('DC', 'Dental cleaning'), ('CR', 'Crowns'), ('BR', 'Braces'), ('TW', 'Teeth whitening')], default='CG', max_length=5),
        ),
    ]
