# Generated by Django 2.2.24 on 2023-03-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0009_auto_20230329_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hour',
            field=models.TimeField(blank=True, null=True, verbose_name=['%H:%M']),
        ),
    ]
