# Generated by Django 2.2.24 on 2023-03-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0012_auto_20230329_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hour',
            field=models.TimeField(blank=True, null=True, unique=True, verbose_name=['%H:%M']),
        ),
    ]
