# Generated by Django 2.2.24 on 2023-04-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0013_auto_20230329_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hour',
        ),
    ]
