# Generated by Django 2.2.24 on 2023-04-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0014_remove_appointment_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
