# Generated by Django 4.2 on 2023-06-01 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0015_remove_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
        ),
    ]
