# Generated by Django 4.2 on 2023-06-02 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='registration_date',
        ),
    ]
